core/urls.py
from . import views
from django.urls import path

app_name = "core"

urlpatterns = [
    path("",views.index,name="index")
]

weather/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core'))
]

core/models.py
from django.db import models

# Create your models here.

class Locations(models.Model):
    location = models.CharField(max_length=20)

    def __str__(self):
        return self.location

    class Meta:
        verbose_name_plural = 'cities'

core/forms.py
from django import forms

class Location(forms.Form):
    location = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter your location'
    }))

core/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from .forms import Location
from .models import Locations
import requests
# Create your views here.

base = 'http://api.openweathermap.org/data/2.5/'
api_key = '18c576b922aa4a57701b077cdd3a4b17'

def index(response):
    if response.method == "POST":
        form = Location(response.POST or None)
        if form.is_valid():
            location = form.cleaned_data['location']
            new_location = Locations(location=location)
            new_location.save()

    all_weather = []
    for loc in Locations.objects.all():
        resp = requests.get(base+'weather?q='+loc.location+'&units=metric&APPID='+api_key).json()
        weather = {
            'city': loc.location,
            'temp': resp['main']['temp'],
            'description': resp['weather'][0]['description'],
            'icon': resp['weather'][0]['icon']
        }
        all_weather.append(weather)
    context = {
        'form': Location(),
        'weather': all_weather
    }
    return render(response, "index.html",context)
    

core/templates/index.html
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

    <title>Weather</title>
  </head>
  <body>
    <h2 class="d-flex justify-content-center">Get weather Updates</h2>
    
    <div class="get-values d-flex justify-content-center mt-5">
        <form action="{% url 'core:index' %}" method="POST">
            {% csrf_token %}
            <div class="md-form mb-5">
                {{ form.location }}
            </div>
            <button type="submit" class="btn btn-md btn-primary ml-4">Submit</button>
        </form>
    </div>
    <div class="container d-flex justify-content-center">
      {% if weather %}
        <ul class="list-unstyled">
        {% for t in weather %}
          <li class="border border-secondary mt-2 rounded"><div>City:{{t.city}}<br>{{t.temp}}°c <br>{{t.description}} <br> <img src="http://openweathermap.org/img/w/{{t.icon}}.png" alt=""></div></li>
        {% endfor %}
        </ul>
      {% endif %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>